import { AuthenProvider } from "./component/authContext"
import Header from "./component/Header"

export const metadata = {
  title: 'English',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://code.responsivevoice.org/responsivevoice.js?key=o8WIu1V7"></script>
      </head>
      <body style={{margin:0}}>
        <AuthenProvider>
          {/* <Header/> */}
          {children}
        </AuthenProvider>
        </body>
    </html>
  )
}
